parameters:
    app.database_url: 'sqlite:///%kernel.project_dir%/var/test/system.brain'
    app.system_database_path: '%kernel.project_dir%/var/test/system.brain'
    app.user_database_path: '%kernel.project_dir%/var/test/user.brain'
    app.setup_lock_path: '%kernel.project_dir%/var/test/.setup.lock'
