# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.database_url: '%env(resolve:DATABASE_URL)%'
    app.system_database_path: '%kernel.project_dir%/var/system.brain'
    app.user_database_path: '%kernel.project_dir%/var/user.brain'
    app.setup_lock_path: '%kernel.project_dir%/var/.setup.lock'
    app.sqlite_busy_timeout_default: 5000
    app.sqlite_busy_timeout_ms: '%env(int:default:app.sqlite_busy_timeout_default:SQLITE_BUSY_TIMEOUT_MS)%'
    app.default_project_slug: 'default'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Doctrine\Middleware\AttachUserDatabaseMiddleware:
        arguments:
            $userDatabasePath: '%app.user_database_path%'
            $busyTimeoutMs: '%app.sqlite_busy_timeout_ms%'
        tags:
            - { name: doctrine.middleware, connection: default }

    App\Module\ModuleRegistry:
        arguments:
            $manifestsData: '%app.modules%'
        public: true

    App\Theme\ThemeRegistry:
        arguments:
            $manifestsData: '%app.themes%'

    App\Setup\SetupState:
        bind:
            $databaseUrl: '%app.database_url%'
            $systemDatabaseFallbackPath: '%app.system_database_path%'
            $userDatabasePath: '%app.user_database_path%'
            $lockFilePath: '%app.setup_lock_path%'

    App\Security\Authorization\ProjectCapabilityVoter:
        tags: ['security.voter']

    App\Security\Capability\CapabilityRegistry: ~

    App\Security\Capability\CapabilitySynchronizer: ~

    App\Translation\CatalogueManager:
        arguments:
            $translator: '@App\Translation\DebugTranslator.inner'

    App\Translation\DebugTranslator:
        decorates: translator
        arguments:
            - '@App\Translation\DebugTranslator.inner'
            - '@request_stack'
            - '@App\Translation\CatalogueManager'

    Doctrine\Migrations\DependencyFactory: '@doctrine.migrations.dependency_factory'

    App\Security\Password\PasswordResetTokenManager: ~

    App\Security\Audit\SecurityAuditLogger: ~

    App\Security\User\AppUserRepository: ~

    App\Controller\Installer\InstallerController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\Debug\LocaleController:
        tags: ['controller.service_arguments']
        public: true

    app.security.remember_me_token_provider:
        class: Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'app_remember_me_token'

    doctrine.orm.messenger.doctrine_schema_listener:
        class: Symfony\Bridge\Doctrine\SchemaListener\MessengerTransportDoctrineSchemaListener
        arguments:
            - []
        tags: []

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
